# Generated by Django 6.0.6 on 2026-06-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id_aerolinea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'aerolinea',
            },
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id_aeropuerto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'db_table': 'aeropuerto',
            },
        ),
        migrations.CreateModel(
            name='TipoAvion',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('alcance', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_avion',
            },
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id_avion', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('id_aerolinea', models.ForeignKey(db_column='id_aerolinea', on_delete=django.db.models.deletion.CASCADE, related_name='aviones', to='vuelos.aerolinea')),
            ],
            options={
                'db_table': 'avion',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('id_avion', models.ForeignKey(db_column='id_avion', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='vuelos.avion')),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id_terminal', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('id_aeropuerto', models.ForeignKey(db_column='id_aeropuerto', on_delete=django.db.models.deletion.CASCADE, related_name='terminales', to='vuelos.aeropuerto')),
            ],
            options={
                'db_table': 'terminal',
            },
        ),
        migrations.CreateModel(
            name='PuertaEmbarque',
            fields=[
                ('id_puerta', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('id_terminal', models.ForeignKey(db_column='id_terminal', on_delete=django.db.models.deletion.CASCADE, related_name='puertas_embarque', to='vuelos.terminal')),
            ],
            options={
                'db_table': 'puerta_embarque',
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vuelo', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vuelo', 'En Vuelo'), ('aterrizado', 'Aterrizado'), ('cancelado', 'Cancelado'), ('demorado', 'Demorado')], default='programado', max_length=20)),
                ('id_avion', models.ForeignKey(db_column='id_avion', on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='vuelos.avion')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['fecha', 'codigo_vuelo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_real_salida', models.DateTimeField(blank=True, null=True)),
                ('hora_real_llegada', models.DateTimeField(blank=True, null=True)),
                ('id_vuelo', models.ForeignKey(db_column='id_vuelo', on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Registro de Vuelo',
                'verbose_name_plural': 'Registros de Vuelo',
                'ordering': ['id_vuelo'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('id_vuelo', models.ForeignKey(db_column='id_vuelo', on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_programada', models.DateTimeField()),
                ('llegada_programada', models.DateTimeField()),
                ('id_vuelo', models.ForeignKey(db_column='id_vuelo', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['salida_programada'],
            },
        ),
        migrations.CreateModel(
            name='ControlTrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizacion', models.CharField(max_length=100)),
                ('hora', models.DateTimeField()),
                ('id_vuelo', models.ForeignKey(db_column='id_vuelo', on_delete=django.db.models.deletion.CASCADE, related_name='controles_trafico', to='vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Control de Tráfico',
                'verbose_name_plural': 'Controles de Tráfico',
                'ordering': ['hora'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(db_column='destino', on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='vuelos.aeropuerto')),
                ('origen', models.ForeignKey(db_column='origen', on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='vuelos.aeropuerto')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['origen', 'destino'],
                'unique_together': {('origen', 'destino')},
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aeropuerto_escala', models.ForeignKey(db_column='aeropuerto_escala', on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='vuelos.aeropuerto')),
                ('id_vuelo', models.ForeignKey(db_column='id_vuelo', on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['id_vuelo'],
                'unique_together': {('id_vuelo', 'aeropuerto_escala')},
            },
        ),
    ]
