# Generated by Django 6.0.6 on 2026-06-27 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='EstadoVuelo',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Vuelo',
                'verbose_name_plural': 'Estados de Vuelo',
                'db_table': 'estado_vuelo',
            },
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id_pista', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pista',
            },
        ),
        migrations.CreateModel(
            name='AutorizacionVuelo',
            fields=[
                ('id_autorizacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_autorizacion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.vuelo')),
            ],
            options={
                'db_table': 'autorizacion_vuelo',
            },
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id_clima', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('condicion', models.CharField(max_length=100)),
                ('velocidad_viento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climas', to='vuelos.aeropuerto')),
            ],
            options={
                'verbose_name': 'Clima',
                'verbose_name_plural': 'Climas',
                'db_table': 'clima',
            },
        ),
        migrations.CreateModel(
            name='AsignacionTripulacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.vuelo')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.empleado')),
            ],
            options={
                'db_table': 'asignacion_tripulacion',
            },
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id_piloto', models.AutoField(primary_key=True, serialize=False)),
                ('licencia', models.CharField(max_length=50, unique=True)),
                ('id_empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vuelos.empleado')),
            ],
            options={
                'db_table': 'piloto',
            },
        ),
        migrations.CreateModel(
            name='AsignacionPista',
            fields=[
                ('id_asignacion_pista', models.AutoField(primary_key=True, serialize=False)),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.vuelo')),
                ('id_pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.pista')),
            ],
            options={
                'db_table': 'asignacion_pista',
            },
        ),
        migrations.CreateModel(
            name='TorreControl',
            fields=[
                ('id_torre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=20)),
                ('id_aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.aeropuerto')),
            ],
            options={
                'db_table': 'torre_control',
            },
        ),
        migrations.CreateModel(
            name='Tripulacion',
            fields=[
                ('id_tripulacion', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=50)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.empleado')),
            ],
            options={
                'db_table': 'tripulacion',
            },
        ),
    ]
