# Generated by Django 6.0.6 on 2026-06-27 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_empleado_estadovuelo_pista_autorizacionvuelo_clima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='historial_estados', to='vuelos.estadovuelo')),
                ('id_vuelo', models.ForeignKey(db_column='id_vuelo', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Historial Estado Vuelo',
            },
        ),
    ]
