# Generated by Django 6.0.6 on 2026-07-13 20:31

import vuelos.models.aerolinea
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerolinea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vuelos.models.aerolinea.product_image_path),
        ),
    ]
