# Generated by Django 6.0.6 on 2026-07-14 03:47

import vuelos.models.aeropuerto
import vuelos.models.avion
import vuelos.models.empleado
import vuelos.models.piloto
import vuelos.models.tipo_avion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0005_aerolinea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vuelos.models.aeropuerto.aeropuerto_image_path),
        ),
        migrations.AddField(
            model_name='avion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vuelos.models.avion.avion_image_path),
        ),
        migrations.AddField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vuelos.models.empleado.empleado_image_path),
        ),
        migrations.AddField(
            model_name='piloto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vuelos.models.piloto.piloto_image_path),
        ),
        migrations.AddField(
            model_name='tipoavion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vuelos.models.tipo_avion.tipo_avion_image_path),
        ),
    ]
