# Generated by Django 6.0.6 on 2026-07-20 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0007_vuelo_asientos_disponibles_vuelo_precio_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='ruta',
            field=models.ForeignKey(blank=True, db_column='id_ruta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='vuelos.ruta'),
        ),
    ]
