# Generated by Django 6.0.6 on 2026-07-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0008_vuelo_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
